### ISSUE TITLE
Select monitor the script renders to

### ISSUE THREAD

**Issue by BuddhiLW** [Zayac-The-Engineer/lazywal-cli#5]
Any ideia how would you go about rendering the wallpaper to a specific port?

**Comment by FabricatorZayac** [comment]
I am not sure if xwinwrap can output to a specific monitor, but I couldn't really test it, cause I only have one.

**Comment by BuddhiLW** [comment]
I changed these lines, and it worked.
```shell
xwinwrap_args="-g 2560x1080+1920 -ni -b -st -un -o 1.0 -ov -debug"
mpv_args="-wid WID --loop --no-audio --no-resume-playback --panscan=1.0"
```

(my HDMI is on the right (+1920) of my laptop screen)

**Comment by BuddhiLW** [comment]
I'm thinking of writing an input pass to the function which utilize these parameters. So, given the size and location of the second monitor (in relation to the virtual displacement), it is able to render the gif wallpaper in just one screen.

What do you think?

**Comment by FabricatorZayac** [comment]
That sounds great! I thought of something like that, but I don't really know how to implement it. I'd love to see what you'd come up with.

**Comment by BuddhiLW** [comment]
Great, just made a pull request 🙏 :)
